---
apiVersion: v1
kind: Namespace
metadata:
  name: inmemory-production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inmemory-http
  name: inmemory-http
  namespace: inmemory-production
spec:
  replicas: 4
  selector:
    matchLabels:
      app: inmemory-http
  strategy:
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: inmemory-http
    spec:
      containers:
      - name: inmemory
        image: localhost:5000/inmemory-search:0.1.0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /_ping
            port: 8080
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 4
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /_ping
            port: 8080
