apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - image: gcr.io/{{ project_id }}/bukukas-inmemory-search:{{ image_version }} # since we don't have real gcr project, just using placeholders for prject-id  / image version
          imagePullPolicy: IfNotPresent
          name: bukukas
          ports:
            - containerPort: 8080
