apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bukukas-inmemory-ingress
  namespace: bukukas-inmemory-production
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: bukukas-inmemory
            port:
              number: 80
  tls:
  - hosts:
    - bukukas-inmemory-search.bukukas.co.id
    secretName: coid
