apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: go-hostname-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: my-app-service
              servicePort: 80
