apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bukukas-inmemory-ingress
  namespace: bukukas-inmemory-production
spec:
  rules:
  - host: bukukas-inmemory-search.bukukas.co.id
    http:
      paths:
      - backend:
          serviceName: bukukas-inmemory
          servicePort: 80
        path: /
  tls:
  - hosts:
    - bukukas-inmemory-search.bukukas.co.id
    secretName: coid
