apiVersion: v1
kind: Service
metadata:
  name: inmemory-http
  namespace: inmemory-production
  labels:
    app: inmemory-http
spec:
  type: NodePort
  selector:
    app: inmemory-http
  ports:
  - port: 3050
    nodePort: 30070
    protocol: TCP
    targetPort: 8080
