apiVersion: v1
kind: Service
metadata:
  name: bukukas-inmemory-http
  namespace: bukukas-inmemory-production
  labels:
    app: bukukas-inmemory-http
spec:
  type: NodePort
  selector:
    app: bukukas-inmemory-http
  ports:
  - port: 3050
    nodePort: 30070
    protocol: TCP
    targetPort: 8080
